variable "realm_name" { type = string }
variable "display_name" { type = string }
variable "smtp" { type = any }
variable "themes" { type = any }
variable "localization" { type = any }
variable "security_headers" { type = any }
variable "password_policy" { type = string }
variable "token_settings" { type = any }
variable "session_settings" { type = any }
variable "brute_force" { type = any }
variable "login_settings" { type = any }
variable "otp_policy" { type = any }
variable "webauthn" { type = any }
variable "webauthn_passwordless" { type = any }
variable "event_settings" { type = any }
variable "realm_attributes" { type = map(string) }
variable "components" { type = any }
variable "organizations" { type = any }
variable "verifiable_credentials" { type = any }
variable "default_realm_roles" { type = list(string) }
variable "roles" { type = any }
variable "groups" { type = any }
variable "users" {
  type      = any
  sensitive = true
}
variable "ldap_federation" { type = any }
variable "google_identity_provider" { type = any }
variable "azuread_identity_provider" { type = any }
variable "apple_identity_provider" { type = any }
